### ISSUE TITLE
Unrecognized contact

### ISSUE THREAD

**Issue by reinforce** [EionRobb/skype4pidgin#432]
Hello,

Strange problem appeared recently:
In my contact list began to appear strange contact cid-(5115899665411920643)@outlook.сom
If I delete it, it reappears again after some time or after restarting Pidgin.
In original Skype client and Skype Web I don't have this contact.

The problem appears to have emerged following the rejection add a new contact.

I use Gentoo Linux, Pidgin 2.10.11 (libpurple 2.10.11) + Skype (HTTP) plugin (version 1.1)

**Comment by EionRobb** [comment]
That's not "yourself" is it?
Can you right click on the contact and choose "Get Info" and paste a screenshot of the popup here?

**Comment by reinforce** [comment]
I try to get info, but informataion window is empty.
And if I'm online, this contact may be offline? but present in my contact list.
Also I have no any @outlook.com addresses.
![-](https://cloud.githubusercontent.com/assets/1038834/15348670/4ed0197a-1cd5-11e6-86f4-45fae2c6c366.png)

**Comment by monsta** [comment]
> You are right, it seems that contact is me. Changing online/away/other statuses in Skype it also changes for this contact in Pidgin.

Thanks - I was wondering who's that in my contact list, and google showed me this issue :smile:

Is it possible to add a filter for it to the skype plugin?

**Comment by MikkCZ** [comment]
I have the same issue, but with cid-(-444834703041191325)@outlook.com. The contact info window is blank.

**Comment by hetdegon** [comment]
I am not sure if it's related, but in addition to the mysterious cid-(*)@outlook.com entry, I also get contacts that I removed in my buddy list. I verified they are gone in web.skype.com, mobile and windows client but deleting them in pidgin is futile, they keep reappearing every time they change status, similar to this cid-(*)@outlook.com entry. Could it have some sort of relation?

**Comment by Monsterovich** [comment]
I can't find a function where library handles all users. The solution is very simple:

```C
if (strstr(username, "cid-(") != NULL && strstr(username, ")@outlook.com") != NULL)
Remove();
```

**Comment by ptkovsky** [comment]
I'm having same exact issue.

**Comment by poisonby** [comment]
I'm having the same issue. Though I haven't tried adding anyone.

**Comment by fanningert** [comment]
I get the same issue. But I think it is a problem from skype.
http://answers.microsoft.com/en-us/msoffice/forum/msoffice_sfb/problem-with-some-skype-contacts-showing-as-cid/b5b4037a-710d-4762-a1dd-ce796faf2909?auth=1

**Comment by alexolog** [comment]
"Resolution: This has been fixed in the Skype service.  No action is required for end users to benefit from this fix - contact federation between Skype for Business and Skype users functions as intended."
-- https://support.microsoft.com/en-us/kb/3163048?sd=rss&spid=17514

**Comment by alaricljs** [comment]
How does that resolve this issue?  I just started using this plugin today and this cid-() account is on my contact list.

**Comment by Monsterovich** [comment]
Indeed.

**Comment by poisonby** [comment]
@alexolog I'm pretty sure that issue is separate from ours. This has nothing to do with Skype for Buesiness (at least I've never used it personally).

**Comment by email200202** [comment]
This is not resolved. I have today the same issue of cid-{}@outlook.com account in my contact list.

**Comment by alaricljs** [comment]
Interestingly mine disappears on occasion for as much as a few hours.  It does not coincide with anything action I've taken however.

**Comment by dequis** [comment]
I'm not sure I understand the problem here. Is this just a matter of having one additional entry in the buddy list? Just the fact that it's annoying to have the thing there?

**Comment by arcctgx** [comment]
I just started using version 1.2.2 today, and I have the same problem.
@dequis The point is only that this entry is unexpected, and shouldn't appear. I don't remember having myself in the list of Skype contacts, and certainly not with such a strange name.

**Comment by LumKitty** [comment]
Still happenning. Doesn't happen in official Skype apparently the "fix" is to link your Skype account to an MS account, but I'm unwilling to do that for various reasons.

**Comment by EionRobb** [comment]
It's "still happening" because there's been no change to fix it :)

What you say about linking accounts to fix is incorrect.  The cid-* contact will display regardless of having a linked account or not.

**Comment by Monsterovich** [comment]
> The cid-* contact will display regardless of having a linked account or not.

Can we just filter this *fake* account by its name?

**Comment by robert-scheck** [comment]
I'm not sure if that "cid-*" contact is really myself, it sometimes changes away status while I did not change it (also no other Skype client connected). But if it's still me, is there any way to detect that within skypeweb already and simply hide that dummy contact?

**Comment by aidaho** [comment]
First I was annoyed by this, but now I think it's a pretty cool feature.  

I've renamed this contact as '*scratch*' and have been using it to share urls between my machines.  
If there will be a push for hiding 'self' contact, I think it would be better made as an option.

**Comment by EionRobb** [comment]
With that latest change you can delete the cid- buddy and they won't come back when you next reconnect to the account.

If others could verify that it's working alright, that would be appreciated :)

**Comment by reinforce** [comment]
@EionRobb 
It looks like everything is fine, after removing this contact no longer appears

**Comment by EionRobb** [comment]
Thanks for the feedback, @reinforce  :)

**Comment by alexolog** [comment]
When I removed the CID account and relaunched Pidgin it promptly got recreated.
I think closing the ticket is premature.
Or is there a new release I am not aware of?

**Comment by EionRobb** [comment]
@alexolog you'll need to compile the plugin to see the change (or grab a new dll from https://eion.robbmob.com/libskypeweb-debug.dll )

**Comment by alexolog** [comment]
It would be nice it there was some way to be notified that a new version is available.
Perhaps you could add a release when you make changes?  There are tools that scan "starred" repositories for new releases and send notifications.

**Comment by EionRobb** [comment]
@alexolog yes, planning on making a release Soon™ but just wanting testers for the things I've fixed before making that release

**Comment by monsta** [comment]
Works for me, thanks :slightly_smiling_face:
