### ISSUE TITLE
Skype bots

### ISSUE THREAD

**Issue by lmfardin** [EionRobb/skype4pidgin#622]
Is there a way to get rid of Skype bots in the contacts list?
I get to see Support Bot and Translator each time I log into Pidgin.
Removing them from both Skype and Pidgin doesn't work.

**Comment by lmfardin** [comment]
Wow, no response at all

**Comment by EionRobb** [comment]
If you remove them from web.skype.com, do they stay gone?

**Comment by lmfardin** [comment]
Yesterday, I removed the bot from Skype app and now they no longer show up on either web.skype.com or Pidgin. I guess it's fixed now, thanks.
    Em quinta-feira, 27 de dezembro de 2018 18:54:17 BRST, Eion Robb <notifications@github.com> escreveu:  
 
 
If you remove them from web.skype.com, do they stay gone?

**Comment by arcctgx** [comment]
@EionRobb I'm having a similar problem. At some point the Translator Bot ans Skype Bot were added to my contact list. I have removed them from the contact list using official Linux Skype application. I also don't see them on web.skype.com. But I can still see Skype Bot (a.k.a. `28:concierge`) in Pidgin contact list. If I remove it from Pidgin, it comes back when I reconnect to Skype.

**Comment by dumol** [comment]
@arcctgx, have you tried removing the account in Pidgin? Then add it again. If the bot is no longer in the server-side list, it shouldn't appear in Pidgin either.

Disclaimer: just a regular Pidgin user here, retrying Skype after a long hiatus.

**Comment by arcctgx** [comment]
@dumol Removing the bot from my contact list in Pidgin doesn't help, it always comes back.

I created completely fresh Pidgin profile and added my Skype account. The bot was imported with all my real contacts. I guess "removing" the bot server-side only hides it from the contact list.

**Comment by dumol** [comment]
I actually meant just removing the Skype account from Pidgin and re-adding it after removing the contacts from an Skype client. But I can confirm that doesn't work either, the deleted contacts re-appear again in Pidgin.
